import { base } from '$app/paths';

const article_1 = {
    "id": 1,
    "title": "DCC 2024",
    "description": "AIDetx: a compression-based method for identification of machine-learning generated text",
    "tags": [
        "compression", "paper",
    ],
    "md":
`
# AIDetx

<div style="text-align: justify;">
Me and my colleagues Pedro Rogrigues and Leonardo Almeida, under the supervision of Professors Diogo Pratas and Armando Pinho, developed and published a paper on a compression-based method for identification of machine-learning generated text, named AIDetx. The paper "AIDetx: a compression-based method for identification of machine-learning generated text" was submitted and accepted to the 2024 Data Compression Conference (DCC 2024).
</div>

## Abstract

<div style="text-align: justify;">
This paper introduces AIDetx, a novel method for detecting machine-generated text using data compression techniques. Traditional approaches, such as deep learning classifiers, often suffer from high computational costs and limited interpretability. To address these limitations, we propose a compression-based classification framework that leverages finite-context models (FCMs). AIDetx constructs distinct compression models for human-written and AI-generated text, classifying new inputs based on which model achieves a higher compression ratio. We evaluated AIDetx on two benchmark datasets, achieving F1 scores exceeding 97% and 99%, respectively, highlighting its high accuracy. Compared to current methods, such as large language models (LLMs), AIDetx offers a more interpretable and computationally efficient solution, significantly reducing both training time and hardware requirements (e.g., no GPUs needed). The full implementation is publicly available at https://<!--Comment to break link-->github.com/AIDetx/AIDetx<!--Comment to break link-->.
</div>
<br><br>
<div class="button-container">
    <a href="https://github.com/AIDetx/AIDetx" target="_blank" rel="noreferrer">
        <div class="custom-button">Repository</div>
    </a>
    <a href="https://www.researchgate.net/publication/386334877_AIDetx_a_compression-based_method_for_identification_of_machine-learning_generated_text" target="_blank" rel="noreferrer">
        <div class="custom-button">Paper</div>
    </a>
</div>


<style>
    .button-container {
		display: flex;
		gap: 10px; /* Add spacing between the buttons */
	}

    .custom-button {
        padding: 10px 20px;
        color: white;
        text-align: center;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
        font-size: 16px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        display: flex;
		justify-content: center;
		align-items: center;
		color: white;
		border: 2px solid white;
    }

</style>
`
}

const article_2 = {
    "id": 2,
    "title": "Aveiro Tech City Hackathon 2024",
    "description": "Winning Team of the Aveiro Tech City Hackathon 2024 - Altice Labs Challenge",
    "tags": [
        "hackathon", "altice labs"
    ],
    "md":
`
# Altice Labs Challenge

<div style="text-align: justify;">
Me and my colleagues Pedro Rodrigues, Leonardo Almeida and Rafael Gonçalves, under the team name "HackaTeam", participated and won the challenge from Altice Labs: "MEDIA DIVE - Novas Formas de Interação na TV com Conteúdo Enriquecido: Um Caminho Promissor" at the Aveiro Tech City Hackathon 2024.
</div>
<br>
<div style="text-align: justify;">
The challenge consisted of developing a new way of interacting with MEO TV by utilizing enriched metadata provided by the MEDIA DIVE API, which offered accesses to transcripts, keywords, thumbnails, and more of some given TV channels.
</div>
<br>
<div style="text-align: justify;">
Our solution consisted of an end-to-end system that identifies the user profile accessing the contents, as there can be multiple types of users using the same TV, and creates a personalized experience. Instead of traditional channels lists, our system shows engaging and appealing summaries generated by combining the enriched metadata from the MEDIA DIVE API with the capabilities of large language models (LLMs) to condense show content based on its transcripts.
</div>
<br>
<div class="button-container">
    <a href="${base}/files/hackaton_cert.pdf" target="_blank" rel="noreferrer">
        <div class="custom-button">Certificate</div>
    </a>
</div>

![Aveiro Tech City Hackathon 2024](${base}/images/hackaton.png)

<style>
    .button-container {
		display: flex;
		gap: 10px; /* Add spacing between the buttons */
	}

    .custom-button {
        padding: 10px 20px;
        color: white;
        text-align: center;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
        font-size: 16px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        display: flex;
		justify-content: center;
		align-items: center;
		color: white;
		border: 2px solid white;
    }

</style>
`
}

const article_3 = {
    "id": 3,
    "title": "UA Webinar",
    "description": "How to comply with the written presentation rules for UA theses and dissertations",
    "tags": [
        "webinar", "ua"
    ],
    "md":
`
# How to comply with the written presentation rules for UA theses and dissertations

<div style="text-align: justify;">
On 22 October 2024, I participated in a webinar organized by the University of Aveiro Library to present the rules for the written presentation of theses and dissertations. The webinar was presented by Alberto Jesus.
<br><br>
The webinar covered a range of essential topics, such concers on the thesis structure and content, formatting requirements, and the submission process. It also highlighted common errors to avoid when preparing a thesis and offered practical tips for enhancing the overall quality of the document.
</div>
<br>
<div class="button-container">
    <a href="${base}/files/webinar.pdf" target="_blank" rel="noreferrer">
        <div class="custom-button">Certificate</div>
    </a>
</div>

<style>
    .button-container {
		display: flex;
		gap: 10px; /* Add spacing between the buttons */
	}

    .custom-button {
        padding: 10px 20px;
        color: white;
        text-align: center;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
        font-size: 16px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
        display: flex;
		justify-content: center;
		align-items: center;
		color: white;
		border: 2px solid white;
    }
</style>
`
}

const article_4 = {
    "id": 4,
    "title": "Dissertations Defenses",
    "description": "Attended to multiple dissertation defenses from DETI",
    "tags": [
        "dissertation", "defense"
    ],
    "md":
`
<div style="text-align: justify;">
Attended to 3 dissertation defenses of the Master's in Informatics Engineering and the Master's in Computational Engineering at the University of Aveiro. Two of these dissertation defenses were very related to my dissertation area, and one was even related to my dissertation topic.
<br><br>
The importance of attending to these defenses was to understand the structure and content of a dissertation defense, the avaliation criteria, the questions asked by the jury, as well as to learn from the mistakes and successes of the students who defended their dissertations.
</div>
`
}

const blogs = [
    article_2,
    article_1,
    article_3,
    article_4
  ]

  
export default blogs;
